export const config = {
  coupleNames: "Abdul Rehman & Rukhsaar",
  eventDate: "2025-11-05",
  groom: "Abdul Rehman",
  groomNickName: "Rehman",
  groomInstagram: "",
  groomBio: "With love and faith",
  bride: "Rukhsaar",
  brideNickName: "Rukhsaar",
  brideInstagram: "",
  brideBio: "With love and grace",
  bibleVerse: "White & Gold Wedding - 5th Nov",
  bibleVerseContent: "Two souls, one heart",
  timeline_1: "Our Journey Begins",
  timeline_1_content: "The start of a beautiful story",
  timeline_2: "The Proposal",
  timeline_2_content: "A moment to remember",
  timeline_3: "Wedding Day - 5th Nov 2025",
  timeline_3_content: "White & Gold Celebration",
  timeline_3_date: "2025-11-05",
  holyMatrimony: {
    title: "Holy Matrimony",
    date: "2025-11-05",
    time: "11:00 AM",
    location: "Main Hall"
